version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout      
      - run:
          name: Update
          command: apt-get update
      - run:
          name: Install Autoconf
          command: apt-get install autoconf
      - run:
          name: Install Automake
          command: apt-get install automake
      - run:
          name: Install Libtool
          command: apt-get install libtool
      # - run:
      #     name: Install Xerces-c
      #     command: yum install xerces-c
      # - run:
      #     name: Install MySQL Connector C
      #     command: apt-get install mysql-connector-c
      # - run:
      #     name: Install Armadillo
      #     command: apt-get install armadillo
      - run: |
        autoreconf -isf
        ./configure --enable-silent-rules --prefix=$PWD/install
        make -j install