version: 2
jobs:
  build:
    docker:
      - image: fedora
    steps:
      - checkout            
      - run:
          name: Update
          command: sudo apt-get update
      - run:
          name: Install Autoconf
          command: sudo apt-get install autoconf
      - run:
          name: Install Automake
          command: sudo apt-get install automake
      - run:
          name: Install Libtool
          command: sudo apt-get install libtool
      - run:
          name: Install Xerces-c
          command: sudo apt-get install libxerces-c-dev
      - run:
          name: Install MySQL Connector C
          command: sudo apt-get install libmysqlcppconn-dev
      - run:
          name: Install Armadillo
          command: sudo apt-get install libarmadillo8
      - run:
          name: Autoreconf
          command: autoreconf -isf
      - run:
          name: Configure
          command: ./configure --enable-silent-rules --prefix=$PWD/install
      - run:
          name: Make Install
          command: |
            make
            make install
            make validate
