version: 2
jobs:
  build:
    docker:
      - image: centos/python-36-centos7

    steps:
      - checkout            
      # - run:
      #     name: Update apt get
      #     command: apt-get update      
      - run:
          name: Install Autoconf
          command: yum install autoconf
      - run:
          name: Install Automake
          command: yum install automake
      - run:
          name: Install Libtool
          command: yum install libtool
      - run:
          name: Install Xerces-c
          command: yum install libxerces-c-dev
      - run:
          name: Install MySQL Connector C
          command: yum install libmysqlcppconn-dev
      - run:
          name: Install Armadillo
          command: yum install libarmadillo8
      - run:
          name: Autoreconf
          command: autoreconf -isf
      - run:
          name: Configure
          command: ./configure --enable-silent-rules --prefix=$PWD/install
      - run:
          name: Make Install
          command: |
            make
            make install
            make validate
