version: 2
jobs:
  build:
    docker:
      - image: centos/devtoolset-7-toolchain-centos7
    steps:
      - checkout            
      # - run:
      #     name: Update apt get
      #     command: sudo apt-get update
      - run:
          name: Install Autoconf
          command: yum install autoconf
      - run:
          name: Install Automake
          command: yum install automake
      - run:
          name: Install Libtool
          command: yum install libtool
      - run:
          name: Install Xerces-c
          command: yum install libxerces-c-dev
      - run:
          name: Install MySQL Connector C
          command: yum libmysqlcppconn-dev
      - run:
          name: Install Armadillo
          command: yum libarmadillo8
      - run:
          name: Autoreconf
          command: autoreconf -isf
      - run:
          name: Customization
          command: |
            ./customize status
            ./customize configure status --enable-silent-rules --prefix=/usr/local --with-mysql=/usr/local 'CXXFLAGS=-w -O2' 'CFLAGS=-w -O2'
      - run:
          name: Configure
          command: ./configure --enable-silent-rules --prefix=$PWD/install
      - run:
          name: Make Install
          command: |
            make
            make install
            make validate
