version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    steps:
      - checkout
      - run:
          name: Check the Stream Editor
          command: which sed
      - run:
          name: Update
          command: apt-get update
      - run:
          name: Install Autoconf
          command: apt-get install autoconf
      - run:
          name: Install Automake
          command: apt-get install automake
      - run:
          name: Install Libtool
          command: apt-get install libtool