version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:19.04

    steps:
      - checkout            
      - run:
          name: Update apt get
          command: sudo apt-get update      
      - run:
          name: Install Autoconf
          command: sudo apt-get install autoconf
      - run:
          name: Install Automake
          command: sudo apt-get install automake
      - run:
          name: Install Libtool
          command: sudo apt-get install libtool
      - run:
          name: Install Xerces-c
          command: sudo apt-get install xerces-c
      - run:
          name: Install MySQL Connector C
          command: sudo apt-get install mysql-connector-c
      - run:
          name: Install Armadillo
          command: sudo apt-get install armadillo
      - run:
          name: Autoreconf
          command: autoreconf -isf
      - run:
          name: Configure
          command: ./configure --enable-silent-rules --prefix=$PWD/install
      - run:
          name: Make Install
          command: make -j install