version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Initial test of getting CI setup for Gridlab-D.

      - run:
          name: Print the Current Time
          command: date