version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Update
          command: apt-get update
      - run:
          name: Install Autoconf
          command: apt-get autoconf
      - run:
          name: Install Automake
          command: apt-get automake
      - run:
          name: Install Libtool
          command: apt-get libtool
      - run:
          name: Check the Stream Editor
          command: which sed